build: Add Android.bp to support Android build
uftrace is compiled fine but needs more fix because record fails as follows.

Cherry-picked some patches from termux repo.
  https://github.com/termux/termux-packages/tree/master/packages/uftrace

Tested on android emulator.

  marvin:/data/nativetest64 # ./uftrace record -L. -la -v pwd
  uftrace: running uftrace v0.11-7-gda2b ( x86_64 perf sched )
  uftrace: checking binary /system/bin/pwd
  uftrace: removing uftrace.data.old directory
  uftrace: creating 1 thread(s) for recording
  uftrace: using ./libmcount.so library for tracing
  mcount: initializing mcount library
  symbol: error during open symbol file: /dev/__properties__/u:object_r:heapprofd_prop:s0: Success
  symbol: error during open symbol file: /dev/__properties__/u:object_r:heapprofd_prop:s0: Success
  symbol: error during open symbol file: /dev/__properties__/u:object_r:exported2_default_prop:s0: Success
  symbol: error during open symbol file: /dev/__properties__/u:object_r:exported2_default_prop:s0: Success
  symbol: error during open symbol file: /dev/__properties__/u:object_r:debug_prop:s0: Success
  symbol: error during open symbol file: /dev/__properties__/u:object_r:debug_prop:s0: Success
  symbol: error during open symbol file: /dev/__properties__/properties_serial: Success
  symbol: error during open symbol file: /dev/__properties__/properties_serial: Success
  symbol: error during open symbol file: /dev/__properties__/property_info: Success
  symbol: error during open symbol file: /dev/__properties__/property_info: Success
  symbol: error during open symbol file: /dev/__properties__/u:object_r:vendor_socket_hook_prop:s0: Success
  symbol: error during open symbol file: /dev/__properties__/u:object_r:vendor_socket_hook_prop:s0: Success
  symbol: error during open symbol file: /dev/__properties__/u:object_r:vndk_prop:s0: Success
  symbol: error during open symbol file: /dev/__properties__/u:object_r:vndk_prop:s0: Success
  dwarf: prepare debug info
  plthook: setup nested PLT hooking "/system/bin/toybox"
  plthook: error when hooking plt: skipping...
  mcount: mcount setup done
  mcount: new session started: afb75b5eaadc9646: toybox
  mcount: failed to open shmem buffer: /uftrace-afb75b5eaadc9646-2092-000
  mcount: vendor/example/uftrace/libmcount/record.c:121:prepare_shmem_buffer
   ERROR: mmap shmem buffer: No such file or directory
  uftrace: child terminated with exit code: 1
  uftrace: reading uftrace.data/task.txt file
  symbol: error during open symbol file: /dev/__properties__/u:object_r:heapprofd_prop:s0: Success
  symbol: error during open symbol file: /dev/__properties__/u:object_r:heapprofd_prop:s0: Success
  symbol: error during open symbol file: /dev/__properties__/u:object_r:exported2_default_prop:s0: Success
  symbol: error during open symbol file: /dev/__properties__/u:object_r:exported2_default_prop:s0: Success
  symbol: error during open symbol file: /dev/__properties__/u:object_r:debug_prop:s0: Success
  symbol: error during open symbol file: /dev/__properties__/u:object_r:debug_prop:s0: Success
  symbol: error during open symbol file: /dev/__properties__/properties_serial: Success
  symbol: error during open symbol file: /dev/__properties__/properties_serial: Success
  symbol: error during open symbol file: /dev/__properties__/property_info: Success
  symbol: error during open symbol file: /dev/__properties__/property_info: Success
  symbol: error during open symbol file: /dev/__properties__/u:object_r:vendor_socket_hook_prop:s0: Success
  symbol: error during open symbol file: /dev/__properties__/u:object_r:vendor_socket_hook_prop:s0: Success
  symbol: error during open symbol file: /dev/__properties__/u:object_r:vndk_prop:s0: Success
  symbol: error during open symbol file: /dev/__properties__/u:object_r:vndk_prop:s0: Success

Signed-off-by: Honggyu Kim <honggyu.kp@gmail.com>